### ISSUE TITLE
user guides

### ISSUE THREAD

**Issue by PharosAbad** [doganmehmet/PortfolioAnalytics.jl#3]
Good job!

user guides, and examples if any , will be better

**Comment by doganmehmet** [comment]
Thank you for the feedback. Guides and wider documentation are on the way. Hopefully it will be ready within a day or two.

**Comment by doganmehmet** [comment]
The user guide is added to README in GitHub. However, proper documentation is under development. Once ready, links will be added to README.

Can I close this for now?

**Comment by doganmehmet** [comment]
@PharosAbad,
Proper user guide is created and available at
 https://doganmehmet.github.io/PortfolioAnalytics.jl/dev/guide.html

The documentation refers to the development version. 

Readme section of repository also improved. 

I hope it will be useful for you. Please feel free to open issue for any bug or feature request.
